server:
  port: ${TOMCAT_PLAT_PORT:6070}

# Logging settings
## 使用starter log4j2省略log4j2.xml文件
logging:
  file:
    path: ./
    name: specified.log
    max-size: 20MB

# Spring settings
spring:


# Gateway Setting
## 暂时不支持往多台网关发送数据
gateway:
  server-address: tbox.zs.incarcloud.com
  read-file: false
  server-port: 6667